### ISSUE TITLE
CSS Customizations

### ISSUE THREAD

**Issue by titieo** [Hejtmus/svelte-fullpage#57]
**Is your feature request related to a problem? Please describe.**
So I want to style the switching slide buttons, though currently Im doing so with pretty weird classes, so it would be better if you could you add a class so it's easier to customize those with css.

This is for the switching buttons and this seem pretty weird lol:
```css
div.svelte-tl5y4n {
  opacity: 0;
  transition: all 200ms;
}
div.svelte-tl5y4n:hover {
  opacity: 1;
}
```
